/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhotde2View;

import conexaoBd.ConexaoBd;
import conexaoBd.ControleCliente;
import conexaoBd.ControleEndereco;
import conexaoBd.ModeloTabela;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.ClienteModel;

/**
 *
 * @author joaoc
 */
public class Cadastro_Cliente extends javax.swing.JFrame {

    ConexaoBd conEnd = new ConexaoBd();
    ConexaoBd conCli = new ConexaoBd();
    ClienteModel mod = new ClienteModel();

    ControleCliente control = new ControleCliente();

    public Cadastro_Cliente() {
        initComponents();
        conEnd.conectar();
        conCli.conectar();
        
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jfnasc.setFormatterFactory(new DefaultFormatterFactory(form));
             form = new MaskFormatter("###.###.###-##");
            cpf.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }

        
        PreencherTabela("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");
        
        conEnd.executaSQL("select * from endereco order by bairro");

        try {
            conEnd.rs.first();
            jComboBoxEnd.removeAllItems();
            do {
                jComboBoxEnd.addItem(conEnd.rs.getString("bairro"));
            } while (conEnd.rs.next());

        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Erro os preencher o comboBox!!" + ex);

        }
        //conEnd.desconectar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        codc = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        org = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCli = new javax.swing.JTable();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_cancelarL = new javax.swing.JButton();
        jComboBoxEnd = new javax.swing.JComboBox<>();
        jfnasc = new javax.swing.JFormattedTextField();
        ee = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        e = new javax.swing.JButton();
        d = new javax.swing.JButton();
        cpf = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("CODIGO CLIENTE");

        codc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        codc.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        codc.setEnabled(false);

        jLabel2.setText("NOME");

        nome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        rg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel5.setText("ORGAO");

        org.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel6.setText("DATA DE NASCIMENTO");

        tabelaCli.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaCli);

        bt_salvar.setText("SALVAR");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setText("EDITAR");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setText("EXCLUIR");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_cancelarL.setText("NOVO");
        bt_cancelarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarLActionPerformed(evt);
            }
        });

        jComboBoxEnd.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jfnasc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        ee.setText("<<");
        ee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeActionPerformed(evt);
            }
        });

        dd.setText(">>");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        e.setText("<");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        d.setText(">");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        cpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jLabel8.setText("BAIRRO");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 812, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 465, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(org, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(codc, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(50, 50, 50)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(bt_salvar)
                                .addGap(37, 37, 37)
                                .addComponent(bt_editar)
                                .addGap(39, 39, 39)
                                .addComponent(bt_excluir)
                                .addGap(46, 46, 46)
                                .addComponent(bt_cancelarL)
                                .addGap(48, 48, 48)
                                .addComponent(ee)
                                .addGap(18, 18, 18)
                                .addComponent(dd)
                                .addGap(18, 18, 18)
                                .addComponent(e)
                                .addGap(18, 18, 18)
                                .addComponent(d))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(codc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEnd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(org, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jfnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(rg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(32, 32, 32)))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_salvar)
                    .addComponent(bt_editar)
                    .addComponent(bt_excluir)
                    .addComponent(bt_cancelarL)
                    .addComponent(ee)
                    .addComponent(dd)
                    .addComponent(e)
                    .addComponent(d))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("CADASTRO DE CLIENTES");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed
        //conCli.conectar();

        try {

            mod.setNome(nome.getText());
            mod.setCpf(cpf.getText());
            mod.setRg(rg.getText());
            mod.setOrgao(org.getText());
            mod.setData_nascimento(jfnasc.getText());

            conCli.executaSQL("select * from endereco where bairro='" + jComboBoxEnd.getSelectedItem() + "'");
            conCli.rs.first();

            mod.setCod_end(conCli.rs.getInt("end_id"));

            ControleCliente controle = new ControleCliente();
            controle.inserirCliente(mod);
            PreencherTabela("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");

            
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar cliente\n erro " + ex);
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {
            mod.setCod_cli(Integer.parseInt(codc.getText()));
            mod.setNome(nome.getText());
            mod.setCpf(cpf.getText());
            mod.setRg(rg.getText());
            mod.setOrgao(org.getText());
            mod.setData_nascimento(jfnasc.getText());

            conCli.executaSQL("select * from endereco where bairro='" + jComboBoxEnd.getSelectedItem() + "'");
            conCli.rs.first();
            mod.setCod_end(conCli.rs.getInt("end_id"));
            PreencherTabela("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");

            control.EditarCliente(mod);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao editar cliente\n erro " + ex);
        }
    }//GEN-LAST:event_bt_editarActionPerformed


    private void eeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeActionPerformed

        try {
            conCli.executaSQL("select * from cliente order by cli_id");
            conCli.rs.first();
            codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            nome.setText(conCli.rs.getString("nome"));
            cpf.setText(conCli.rs.getString("cpf"));
            rg.setText(conCli.rs.getString("rg"));
            org.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
            conEnd.rs.first();
            jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eeActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        try {
            conCli.executaSQL("select * from cliente order by cli_id");
            conCli.rs.last();
            codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            nome.setText(conCli.rs.getString("nome"));
            cpf.setText(conCli.rs.getString("cpf"));
            rg.setText(conCli.rs.getString("rg"));
            org.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
            conEnd.rs.first();
            jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_ddActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        try {
            //conCli.executarSQL("select * from cliente order by cli_id");
            conCli.rs.previous();
            codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            nome.setText(conCli.rs.getString("nome"));
            cpf.setText(conCli.rs.getString("cpf"));
            rg.setText(conCli.rs.getString("rg"));
            org.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
            conEnd.rs.first();
            jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        try {
            //conCli.executarSQL("select * from cliente order by cli_id");
            conCli.rs.next();
            codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            nome.setText(conCli.rs.getString("nome"));
            cpf.setText(conCli.rs.getString("cpf"));
            rg.setText(conCli.rs.getString("rg"));
            org.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
            conEnd.rs.first();
            jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_dActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        try {
            mod.setCod_cli(Integer.parseInt(codc.getText()));
            mod.setNome(nome.getText());
            mod.setCpf(cpf.getText());
            mod.setRg(rg.getText());
            mod.setOrgao(org.getText());
            mod.setData_nascimento(jfnasc.getText());
            mod.setCod_end(conCli.rs.getInt("end_id"));
            
            
            control.ExcluirCliente(mod);
            PreencherTabela("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");

        } catch (SQLException ex) {
            Logger.getLogger(Cadastro_Cliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_cancelarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarLActionPerformed
        codc.setText("");
        nome.setText("");
        cpf.setText("");
        rg.setText("");
        org.setText("");
        jfnasc.setText("");

       
    }//GEN-LAST:event_bt_cancelarLActionPerformed

    public void PreencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"codigo Cliente", "Nome", "Cpf ou Cnpj", "rg", "Orgao", "data_nascimento"};

        conCli.executaSQL(SQL);

        try {
            conCli.rs.first();

            do {

                dados.add(new Object[]{
                    conCli.rs.getInt("cli_id"),
                    conCli.rs.getString("nome"),
                    conCli.rs.getString("cpf"),
                    conCli.rs.getString("rg"),
                    conCli.rs.getString("orgao"),
                    conCli.rs.getString("data_nascimento"),
                    
                   
                    
                    
                
                
                
                });

            } while (conCli.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente no arrayList" + ex);
        }

        ModeloTabela model = new ModeloTabela(dados, Colunas);
        tabelaCli.setModel(model);
        tabelaCli.getColumnModel().getColumn(0).setPreferredWidth(50);//cli_id
        tabelaCli.getColumnModel().getColumn(0).setResizable(false);
        tabelaCli.getColumnModel().getColumn(1).setPreferredWidth(300);//nome
        tabelaCli.getColumnModel().getColumn(1).setResizable(false);
        tabelaCli.getColumnModel().getColumn(2).setPreferredWidth(150);//cpf
        tabelaCli.getColumnModel().getColumn(2).setResizable(false);
        tabelaCli.getColumnModel().getColumn(3).setPreferredWidth(100);//rg
        tabelaCli.getColumnModel().getColumn(3).setResizable(false);
        tabelaCli.getColumnModel().getColumn(4).setPreferredWidth(85);//orgao
        tabelaCli.getColumnModel().getColumn(4).setResizable(false);
        tabelaCli.getColumnModel().getColumn(5).setPreferredWidth(120);//data nascimnto
        tabelaCli.getColumnModel().getColumn(5).setResizable(false);
        
        
       

        //tabelaEnd.getColumnModel().getColumn(8).setPreferredWidth(120);
        //tabelaEnd.getColumnModel().getColumn(8).setResizable(false);
        tabelaCli.getTableHeader().setReorderingAllowed(false);
        tabelaCli.setAutoResizeMode(tabelaCli.AUTO_RESIZE_OFF);
        tabelaCli.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_cancelarL;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JTextField codc;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton d;
    private javax.swing.JButton dd;
    private javax.swing.JButton e;
    private javax.swing.JButton ee;
    private javax.swing.JComboBox<String> jComboBoxEnd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField jfnasc;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField org;
    private javax.swing.JTextField rg;
    private javax.swing.JTable tabelaCli;
    // End of variables declaration//GEN-END:variables
}
