/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhotde2View;

import conexaoBd.ConexaoBd;
import conexaoBd.ModeloTabela;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.EnderecoModel;

/**
 *
 * @author joaoc
 */
public class Cadastro_Endereco extends javax.swing.JFrame {

    ConexaoBd conexao = new ConexaoBd();

    /**
     * Creates new form Cadastro_Endereco
     */
    public Cadastro_Endereco() {
        initComponents();
        conexao.conectar();
        
        try {
            MaskFormatter form = new MaskFormatter("##.###-###");
            cep.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
       PreencherTabela("select * from endereco order by end_id");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        code = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        log = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        comp = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        bar = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        num = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cid = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        est = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        bt_novo = new javax.swing.JButton();
        bt_salvar = new javax.swing.JButton();
        bt_editar = new javax.swing.JButton();
        bt_excluir = new javax.swing.JButton();
        bt_cancelar = new javax.swing.JButton();
        ee = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        e = new javax.swing.JButton();
        d = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaEnd = new javax.swing.JTable();
        cep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        code.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        code.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        code.setEnabled(false);

        jLabel1.setText("LOGRADOURO");

        log.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        log.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        log.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logActionPerformed(evt);
            }
        });

        jLabel2.setText("COMPLEMENTO");

        comp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        comp.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel3.setText("BAIRRO");

        bar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bar.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel4.setText("NUMERO");

        num.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        num.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel5.setText("CEP");

        cid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        cid.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel6.setText("CIDADE");

        jLabel7.setText("ESTADO");

        est.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        est.setDisabledTextColor(new java.awt.Color(51, 51, 51));

        jLabel8.setText("CODIGO");

        bt_novo.setText("NOVO");
        bt_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_novoActionPerformed(evt);
            }
        });

        bt_salvar.setText("SALVAR");
        bt_salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_salvarActionPerformed(evt);
            }
        });

        bt_editar.setText("EDITAR");
        bt_editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_editarActionPerformed(evt);
            }
        });

        bt_excluir.setText("EXCLUIR");
        bt_excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_excluirActionPerformed(evt);
            }
        });

        bt_cancelar.setText("CANCELAR");
        bt_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_cancelarActionPerformed(evt);
            }
        });

        ee.setText("<<");
        ee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeActionPerformed(evt);
            }
        });

        dd.setText(">>");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        e.setText("<");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        d.setText(">");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        tabelaEnd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tabelaEnd);

        cep.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        cep.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                                    .addComponent(num))
                                .addGap(48, 48, 48)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(127, 127, 127))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(cep)
                                        .addGap(88, 88, 88)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(42, 42, 42)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(est, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_novo)
                                        .addGap(43, 43, 43)
                                        .addComponent(bt_salvar)
                                        .addGap(51, 51, 51)
                                        .addComponent(bt_editar)))
                                .addGap(36, 36, 36)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(bt_excluir)
                                        .addGap(64, 64, 64)
                                        .addComponent(bt_cancelar)
                                        .addGap(42, 42, 42)
                                        .addComponent(ee)
                                        .addGap(18, 18, 18)
                                        .addComponent(dd)
                                        .addGap(18, 18, 18)
                                        .addComponent(e)
                                        .addGap(18, 18, 18)
                                        .addComponent(d))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(51, 51, 51)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(863, 863, 863)
                        .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1190, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(code, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(log, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(num, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(est, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_novo)
                    .addComponent(bt_salvar)
                    .addComponent(bt_editar)
                    .addComponent(bt_excluir)
                    .addComponent(bt_cancelar)
                    .addComponent(ee)
                    .addComponent(dd)
                    .addComponent(e)
                    .addComponent(d))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("CADASTRO DE ENDEREÇOS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(415, 415, 415)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel9)
                .addGap(36, 36, 36)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_salvarActionPerformed

        try {
            PreparedStatement pst = conexao.conn.prepareStatement("insert into endereco (logradouro, numero, complemento, bairro, cep, cidade, estado)values(?,?,?,?,?,?,?)");
            pst.setString(1, log.getText());
            pst.setString(2, num.getText());
            pst.setString(3, comp.getText());
            pst.setString(4, bar.getText());
            pst.setString(5, cep.getText());
            pst.setString(6, cid.getText());
            pst.setString(7, est.getText());

            pst.executeUpdate();

            JOptionPane.showMessageDialog(rootPane, "adicionado");
            PreencherTabela("select * from endereco order by end_id");
        } catch (SQLException ex) {

            JOptionPane.showMessageDialog(rootPane, "Você digitou errado Tente novamente" + ex);
        }

    }//GEN-LAST:event_bt_salvarActionPerformed

    private void bt_editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_editarActionPerformed
        try {
            //conectado.executarSQL("delete from cliente where nome='"+jnome.getText()+"'");
            // JOptionPane.showMessageDialog(rootPane,"Excluido com Sucesso!!");

            PreparedStatement pst = conexao.conn.prepareStatement("update endereco set logradouro=?, numero=?, complemento=?, bairro=?, cep=?, cidade=?, estado=? where end_id=?");
            pst.setString(1, log.getText());
            pst.setString(2, num.getText());
            pst.setString(3, comp.getText());
            pst.setString(4, bar.getText());
            pst.setString(5, cep.getText());
            pst.setString(6, cid.getText());
            pst.setString(7, est.getText());
            pst.setInt(8, Integer.parseInt(code.getText()));
            pst.execute();

            JOptionPane.showMessageDialog(rootPane, "Editado com Sucesso!!");
            PreencherTabela("select * from endereco order by end_id");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_bt_editarActionPerformed

    private void eeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeActionPerformed

        try {
            conexao.executaSQL("select * from endereco");
            conexao.rs.first();
            code.setText(String.valueOf(conexao.rs.getInt("end_id")));
            log.setText(conexao.rs.getString("logradouro"));
            num.setText(conexao.rs.getString("numero"));
            comp.setText(conexao.rs.getString("complemento"));
            bar.setText(conexao.rs.getString("bairro"));
            cep.setText(conexao.rs.getString("cep"));
            cid.setText(conexao.rs.getString("cidade"));
            est.setText(conexao.rs.getString("estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eeActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        try {
            conexao.executaSQL("select * from endereco");
            conexao.rs.last();
            code.setText(String.valueOf(conexao.rs.getInt("end_id")));
            log.setText(conexao.rs.getString("logradouro"));
            num.setText(conexao.rs.getString("numero"));
            comp.setText(conexao.rs.getString("complemento"));
            bar.setText(conexao.rs.getString("bairro"));
            cep.setText(conexao.rs.getString("cep"));
            cid.setText(conexao.rs.getString("cidade"));
            est.setText(conexao.rs.getString("estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_ddActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        try {
            //conexao.executarSQL("select * from endereco");
            conexao.rs.previous();
            code.setText(String.valueOf(conexao.rs.getInt("end_id")));
            log.setText(conexao.rs.getString("logradouro"));
            num.setText(conexao.rs.getString("numero"));
            comp.setText(conexao.rs.getString("complemento"));
            bar.setText(conexao.rs.getString("bairro"));
            cep.setText(conexao.rs.getString("cep"));
            cid.setText(conexao.rs.getString("cidade"));
            est.setText(conexao.rs.getString("estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        try {
            //conexao.executarSQL("select * from endereco");
            conexao.rs.next();
            code.setText(String.valueOf(conexao.rs.getInt("end_id")));
            log.setText(conexao.rs.getString("logradouro"));
            num.setText(conexao.rs.getString("numero"));
            comp.setText(conexao.rs.getString("complemento"));
            bar.setText(conexao.rs.getString("bairro"));
            cep.setText(conexao.rs.getString("cep"));
            cid.setText(conexao.rs.getString("cidade"));
            est.setText(conexao.rs.getString("estado"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_dActionPerformed

    private void bt_excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_excluirActionPerformed
        try {
            //conectado.executarSQL("delete from cliente where nome='"+jnome.getText()+"'");
            // JOptionPane.showMessageDialog(rootPane,"Excluido com Sucesso!!");

            PreparedStatement pst = conexao.conn.prepareStatement("delete from endereco where logradouro= ?");
            code.setText(String.valueOf(conexao.rs.getInt("end_id")));
            pst.setString(1, log.getText());
            //pst.setString(1, log.getText());

            pst.execute();

            JOptionPane.showMessageDialog(rootPane, "Excluido com Sucesso!!");
            PreencherTabela("select * from endereco order by end_id");
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_bt_excluirActionPerformed

    private void bt_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_cancelarActionPerformed
        code.setText("");
        log.setText("");
        comp.setText("");
        bar.setText("");
        num.setText("");
        cep.setText("");
        cid.setText("");
        est.setText("");

        bt_salvar.setEnabled(false);
        bt_excluir.setEnabled(false);
        bt_editar.setEnabled(false);
        bt_cancelar.setEnabled(false);
        bt_novo.setEnabled(true);

        log.setEnabled(false);
        comp.setEnabled(false);
        bar.setEnabled(false);
        num.setEnabled(false);
        cep.setEnabled(false);
        cid.setEnabled(false);
        est.setEnabled(false);
    }//GEN-LAST:event_bt_cancelarActionPerformed

    private void bt_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_novoActionPerformed
      code.setText("");
        log.setText("");
        comp.setText("");
        bar.setText("");
        num.setText("");
        cep.setText("");
        cid.setText("");
        est.setText("");

         log.setEnabled(true);
        comp.setEnabled(true);
        bar.setEnabled(true);
        num.setEnabled(true);
        cep.setEnabled(true);
        cid.setEnabled(true);
        est.setEnabled(true);
       
        
         bt_salvar.setEnabled(true);
        bt_excluir.setEnabled(true);
        bt_editar.setEnabled(true);
       // bt_cancelar.setEnabled(true);
        bt_novo.setEnabled(false);


    }//GEN-LAST:event_bt_novoActionPerformed

    private void logActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_logActionPerformed

    public void PreencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"codigo","logradouro", "numero", "complemento", "bairro", "cep", "cidade", "estado"};

        conexao.executaSQL(SQL);

        try {
            conexao.rs.first();

            do {

                dados.add(new Object[]{
                    conexao.rs.getInt("end_id"),
                    conexao.rs.getString("logradouro"),
                    conexao.rs.getString("numero"),
                    conexao.rs.getString("complemento"),
                    conexao.rs.getString("bairro"),
                    conexao.rs.getString("cep"),
                    conexao.rs.getString("cidade"),
                    conexao.rs.getString("estado")});

            } while (conexao.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente no arrayList" + ex);
        }

        ModeloTabela model = new ModeloTabela(dados, Colunas);
        tabelaEnd.setModel(model);
        tabelaEnd.getColumnModel().getColumn(0).setPreferredWidth(80);//end_id
        tabelaEnd.getColumnModel().getColumn(0).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(1).setPreferredWidth(300);//logradouro
        tabelaEnd.getColumnModel().getColumn(1).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(2).setPreferredWidth(100);//numero
        tabelaEnd.getColumnModel().getColumn(2).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(3).setPreferredWidth(80);//complemento
        tabelaEnd.getColumnModel().getColumn(3).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(4).setPreferredWidth(206);//bairro
        tabelaEnd.getColumnModel().getColumn(4).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(5).setPreferredWidth(120);//cep
        tabelaEnd.getColumnModel().getColumn(5).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(6).setPreferredWidth(150);//cidade
        tabelaEnd.getColumnModel().getColumn(6).setResizable(false);
        tabelaEnd.getColumnModel().getColumn(7).setPreferredWidth(150);//estado
        tabelaEnd.getColumnModel().getColumn(7).setResizable(false);
        //tabelaEnd.getColumnModel().getColumn(8).setPreferredWidth(120);
        //tabelaEnd.getColumnModel().getColumn(8).setResizable(false);

        tabelaEnd.getTableHeader().setReorderingAllowed(false);
        tabelaEnd.setAutoResizeMode(tabelaEnd.AUTO_RESIZE_OFF);
        tabelaEnd.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cadastro_Endereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cadastro_Endereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bar;
    private javax.swing.JButton bt_cancelar;
    private javax.swing.JButton bt_editar;
    private javax.swing.JButton bt_excluir;
    private javax.swing.JButton bt_novo;
    private javax.swing.JButton bt_salvar;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cid;
    private javax.swing.JTextField code;
    private javax.swing.JTextField comp;
    private javax.swing.JButton d;
    private javax.swing.JButton dd;
    private javax.swing.JButton e;
    private javax.swing.JButton ee;
    private javax.swing.JTextField est;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField log;
    private javax.swing.JTextField num;
    private javax.swing.JTable tabelaEnd;
    // End of variables declaration//GEN-END:variables
}
