/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package trabalhotde2View;

import conexaoBd.ConexaoBd;
import conexaoBd.ControleCliente;
import conexaoBd.ModeloTabela;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;
import model.ClienteModel;

/**
 *
 * @author joaoc
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBd conexao = new ConexaoBd();
    ConexaoBd conCli = new ConexaoBd();
    
    ClienteModel mod = new ClienteModel();
    ControleCliente control = new ControleCliente();
    
    int flag =1;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        //setExtendedState(MAXIMIZED_BOTH);
        conexao.conectar();
        conCli.conectar();
        
        try {
            MaskFormatter form = new MaskFormatter("##/##/####");
            jfnasc.setFormatterFactory(new DefaultFormatterFactory(form));
             form = new MaskFormatter("###.###.###-##");
            jcpf.setFormatterFactory(new DefaultFormatterFactory(form));
             form = new MaskFormatter("##.###-###");
            jcep.setFormatterFactory(new DefaultFormatterFactory(form));
            
        } catch (ParseException ex) {
            Logger.getLogger(TelaPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
        
        PreencherTabela("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jrg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jorg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jcid = new javax.swing.JTextField();
        jesta = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlog = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jcomp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jnum = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jbar = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jfnasc = new javax.swing.JFormattedTextField();
        jcep = new javax.swing.JFormattedTextField();
        jcpf = new javax.swing.JFormattedTextField();
        ee = new javax.swing.JButton();
        dd = new javax.swing.JButton();
        e = new javax.swing.JButton();
        d = new javax.swing.JButton();
        bt_limpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1.setText("CADASTRO CLIENTE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("CADASTRO ENDERECO");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tabela.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela);

        jnome.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jnome.setForeground(new java.awt.Color(0, 0, 0));
        jnome.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jnome.setCaretColor(new java.awt.Color(0, 0, 0));
        jnome.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jnome.setEnabled(false);

        jLabel2.setText("NOME");

        jLabel3.setText("CPF");

        jLabel4.setText("RG");

        jrg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jrg.setForeground(new java.awt.Color(0, 0, 0));
        jrg.setCaretColor(new java.awt.Color(0, 0, 0));
        jrg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jrg.setEnabled(false);

        jLabel5.setText("ORGAO");

        jorg.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jorg.setForeground(new java.awt.Color(0, 0, 0));
        jorg.setCaretColor(new java.awt.Color(0, 0, 0));
        jorg.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jorg.setEnabled(false);

        jLabel6.setText("CIDADE");

        jcid.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcid.setForeground(new java.awt.Color(0, 0, 0));
        jcid.setCaretColor(new java.awt.Color(0, 0, 0));
        jcid.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jcid.setEnabled(false);

        jesta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jesta.setForeground(new java.awt.Color(0, 0, 0));
        jesta.setCaretColor(new java.awt.Color(0, 0, 0));
        jesta.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jesta.setEnabled(false);

        jLabel7.setText("ESTADO");

        jLabel8.setText("LOGRADOURO");

        jlog.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jlog.setForeground(new java.awt.Color(0, 0, 0));
        jlog.setCaretColor(new java.awt.Color(0, 0, 0));
        jlog.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jlog.setEnabled(false);

        jLabel9.setText("COMPLEMENTO");

        jcomp.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jcomp.setForeground(new java.awt.Color(0, 0, 0));
        jcomp.setCaretColor(new java.awt.Color(0, 0, 0));
        jcomp.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jcomp.setEnabled(false);

        jLabel10.setText("NUMERO");

        jnum.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jnum.setForeground(new java.awt.Color(0, 0, 0));
        jnum.setCaretColor(new java.awt.Color(0, 0, 0));
        jnum.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jnum.setEnabled(false);

        jLabel11.setText("DATA NASCIMENTO");

        jLabel12.setText("CEP");

        jbar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbar.setForeground(new java.awt.Color(0, 0, 0));
        jbar.setCaretColor(new java.awt.Color(0, 0, 0));
        jbar.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jbar.setEnabled(false);

        jLabel13.setText("BAIRRO");

        jfnasc.setForeground(new java.awt.Color(0, 0, 0));
        jfnasc.setCaretColor(new java.awt.Color(0, 0, 0));
        jfnasc.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jfnasc.setEnabled(false);
        jfnasc.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jfnasc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jfnascActionPerformed(evt);
            }
        });

        jcep.setForeground(new java.awt.Color(0, 0, 0));
        jcep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##,###.000"))));
        jcep.setCaretColor(new java.awt.Color(0, 0, 0));
        jcep.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jcep.setEnabled(false);
        jcep.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        jcpf.setForeground(new java.awt.Color(0, 0, 0));
        jcpf.setCaretColor(new java.awt.Color(0, 0, 0));
        jcpf.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jcpf.setEnabled(false);
        jcpf.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        ee.setText("<<");
        ee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eeActionPerformed(evt);
            }
        });

        dd.setText(">>");
        dd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ddActionPerformed(evt);
            }
        });

        e.setText("<");
        e.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eActionPerformed(evt);
            }
        });

        d.setText(">");
        d.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dActionPerformed(evt);
            }
        });

        bt_limpar.setText("Limpar");
        bt_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(40, 40, 40)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jrg, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel4))
                                        .addGap(45, 45, 45)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jorg, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(42, 42, 42))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addComponent(jlog, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(37, 37, 37)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jnum, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jbar, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(33, 33, 33)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jcid, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))
                                        .addGap(18, 18, 18)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE)
                                    .addComponent(jfnasc, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jesta)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addGap(43, 43, 43)
                                .addComponent(ee)
                                .addGap(18, 18, 18)
                                .addComponent(dd)
                                .addGap(18, 18, 18)
                                .addComponent(e)
                                .addGap(18, 18, 18)
                                .addComponent(d)
                                .addGap(39, 39, 39)
                                .addComponent(bt_limpar))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jnome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcpf, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(39, 39, 39))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jorg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrg, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jfnasc, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlog, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jnum, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcep, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel13))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jcid, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jesta, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(ee)
                        .addComponent(dd)
                        .addComponent(e)
                        .addComponent(d)
                        .addComponent(bt_limpar))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(227, 227, 227))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("TRABALHO TDE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(525, 525, 525)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Cadastro_Cliente cl = new Cadastro_Cliente();
       cl.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Cadastro_Endereco ce = new Cadastro_Endereco();
        ce.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jfnascActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jfnascActionPerformed
        
    }//GEN-LAST:event_jfnascActionPerformed

    private void tabelaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaMouseClicked
        //conCli.conectar();
        
        
         conCli.executaSQL("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");
        if (flag == 1) {
           
            
            
            String nome = "" + tabela .getValueAt(tabela.getSelectedRow(), 1);
            jnome.setText(nome);
           String cpf = "" + tabela .getValueAt(tabela.getSelectedRow(), 2);
            jcpf.setText(cpf);
             String rg = "" + tabela .getValueAt(tabela.getSelectedRow(), 3);
              jrg.setText(rg);
               String org = "" + tabela .getValueAt(tabela.getSelectedRow(), 4);
               jorg.setText(org);
                String dat = "" + tabela .getValueAt(tabela.getSelectedRow(), 5);
                jfnasc.setText(dat);
                 String log = "" + tabela .getValueAt(tabela.getSelectedRow(), 6);
                 jlog.setText(log);
                 String comp = "" + tabela .getValueAt(tabela.getSelectedRow(), 7);
                 jcomp.setText(comp);
                 String num = "" + tabela .getValueAt(tabela.getSelectedRow(), 8);
                 jnum.setText(num);
                 String cep = "" + tabela .getValueAt(tabela.getSelectedRow(), 9);
                 jcep.setText(cep);
                  String bar = "" + tabela .getValueAt(tabela.getSelectedRow(), 10);
                 jbar.setText(bar);
                  String cid = "" + tabela .getValueAt(tabela.getSelectedRow(), 11);
                  jcid.setText(cid);
                   String esta = "" + tabela .getValueAt(tabela.getSelectedRow(), 12);
                   jesta.setText(esta);
            
            
            
        }
        
        
        
    }//GEN-LAST:event_tabelaMouseClicked

    private void eeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eeActionPerformed

        try {
            conCli.executaSQL("select * from cliente inner join endereco on cliente.end_id = endereco.end_id");
            conCli.rs.first();
            //codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            jnome.setText(conCli.rs.getString("nome"));
            jcpf.setText(conCli.rs.getString("cpf"));
            jrg.setText(conCli.rs.getString("rg"));
            jorg.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));
            jlog.setText(conCli.rs.getString("logradouro"));
            jnum.setText(conCli.rs.getString("numero"));
            jcomp.setText(conCli.rs.getString("complemento"));
            jbar.setText(conCli.rs.getString("bairro"));
            jcep.setText(conCli.rs.getString("cep"));
            jcid.setText(conCli.rs.getString("cidade"));
            jesta.setText(conCli.rs.getString("estado"));

           
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eeActionPerformed

    private void ddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ddActionPerformed
        try {
            conCli.executaSQL("select * from cliente order by cli_id");
            conCli.rs.last();
            //codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            jnome.setText(conCli.rs.getString("nome"));
            jcpf.setText(conCli.rs.getString("cpf"));
            jrg.setText(conCli.rs.getString("rg"));
            jorg.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            //conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
           // conEnd.rs.first();
            //jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_ddActionPerformed

    private void eActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eActionPerformed
        try {
            //conCli.executarSQL("select * from cliente order by cli_id");
            conCli.rs.previous();
           // codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            jnome.setText(conCli.rs.getString("nome"));
            jcpf.setText(conCli.rs.getString("cpf"));
            jrg.setText(conCli.rs.getString("rg"));
            jorg.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));

            //conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
           // conEnd.rs.first();
            //jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_eActionPerformed

    private void dActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dActionPerformed
        try {
            //conCli.executarSQL("select * from cliente order by cli_id");
            conCli.rs.next();
            //codc.setText(String.valueOf(conCli.rs.getInt("cli_id")));
            jnome.setText(conCli.rs.getString("nome"));
            jcpf.setText(conCli.rs.getString("cpf"));
            jrg.setText(conCli.rs.getString("rg"));
            jorg.setText(conCli.rs.getString("orgao"));
            jfnasc.setText(conCli.rs.getString("data_nascimento"));
            
            

            //conEnd.executaSQL("select * from endereco where end_id=" + conCli.rs.getInt("end_id"));
            //conEnd.rs.first();
            //jComboBoxEnd.setSelectedItem(conEnd.rs.getString("bairro"));

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente" + ex);
        }
    }//GEN-LAST:event_dActionPerformed

    private void bt_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_limparActionPerformed
       
        jnome.setText("");
        jcpf.setText("");
        jrg.setText("");
        jorg.setText("");
        jfnasc.setText("");
       
        jlog.setText("");
        jcomp.setText("");
        jbar.setText("");
        jnum.setText("");
        jcep.setText("");
        jcid.setText("");
        jesta.setText("");
    }//GEN-LAST:event_bt_limparActionPerformed

    
    public void PreencherTabela(String SQL) {

        ArrayList dados = new ArrayList();

        String[] Colunas = new String[]{"Cliente", "Nome", "Cpf ou Cnpj", "rg", "Orgao", "data_nascimento", "logradouro","Complemento","numero","cep","Bairro","cidade","estado"};

        conCli.executaSQL(SQL);

        try {
            conCli.rs.first();

            do {

                dados.add(new Object[]{
                    conCli.rs.getInt("cli_id"),
                    conCli.rs.getString("nome"),
                    conCli.rs.getString("cpf"),
                    conCli.rs.getString("rg"),
                    conCli.rs.getString("orgao"),
                    conCli.rs.getString("data_nascimento"),
                    conCli.rs.getString("logradouro"),
                    conCli.rs.getString("complemento"),
                    conCli.rs.getString("numero"),
                    conCli.rs.getString("cep"),
                    conCli.rs.getString("bairro"),
                    conCli.rs.getString("cidade"),
                    conCli.rs.getString("estado")
                    
                
                
                
                });

            } while (conCli.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, " Deu errado Tente novamente no arrayList" + ex);
        }

        ModeloTabela model = new ModeloTabela(dados, Colunas);
        tabela.setModel(model);
        tabela.getColumnModel().getColumn(0).setPreferredWidth(50);//cli_id
        tabela.getColumnModel().getColumn(0).setResizable(false);
        tabela.getColumnModel().getColumn(1).setPreferredWidth(200);//nome
        tabela.getColumnModel().getColumn(1).setResizable(false);
        tabela.getColumnModel().getColumn(2).setPreferredWidth(110);//cpf
        tabela.getColumnModel().getColumn(2).setResizable(false);
        tabela.getColumnModel().getColumn(3).setPreferredWidth(80);//rg
        tabela.getColumnModel().getColumn(3).setResizable(false);
        tabela.getColumnModel().getColumn(4).setPreferredWidth(80);//orgao
        tabela.getColumnModel().getColumn(4).setResizable(false);
        tabela.getColumnModel().getColumn(5).setPreferredWidth(100);//data nascimnto
        tabela.getColumnModel().getColumn(5).setResizable(false);
        tabela.getColumnModel().getColumn(6).setPreferredWidth(170);//data nascimnto
        tabela.getColumnModel().getColumn(6).setResizable(false);
        tabela.getColumnModel().getColumn(7).setPreferredWidth(120);//data nascimnto
        tabela.getColumnModel().getColumn(7).setResizable(false);
        tabela.getColumnModel().getColumn(8).setPreferredWidth(70);//data nascimnto
        tabela.getColumnModel().getColumn(8).setResizable(false);
        tabela.getColumnModel().getColumn(9).setPreferredWidth(80);//data nascimnto
        tabela.getColumnModel().getColumn(9).setResizable(false);
        tabela.getColumnModel().getColumn(10).setPreferredWidth(120);//data nascimnto
        tabela.getColumnModel().getColumn(10).setResizable(false);
       tabela.getColumnModel().getColumn(11).setPreferredWidth(120);//data nascimnto
       tabela.getColumnModel().getColumn(11).setResizable(false);
       tabela.getColumnModel().getColumn(11).setPreferredWidth(120);//data nascimnto
       tabela.getColumnModel().getColumn(11).setResizable(false);

        //tabelaEnd.getColumnModel().getColumn(8).setPreferredWidth(120);
        //tabelaEnd.getColumnModel().getColumn(8).setResizable(false);
        tabela.getTableHeader().setReorderingAllowed(false);
        tabela.setAutoResizeMode(tabela.AUTO_RESIZE_OFF);
        tabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_limpar;
    private javax.swing.JButton d;
    private javax.swing.JButton dd;
    private javax.swing.JButton e;
    private javax.swing.JButton ee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jbar;
    private javax.swing.JFormattedTextField jcep;
    private javax.swing.JTextField jcid;
    private javax.swing.JTextField jcomp;
    private javax.swing.JFormattedTextField jcpf;
    private javax.swing.JTextField jesta;
    private javax.swing.JFormattedTextField jfnasc;
    private javax.swing.JTextField jlog;
    private javax.swing.JTextField jnome;
    private javax.swing.JTextField jnum;
    private javax.swing.JTextField jorg;
    private javax.swing.JTextField jrg;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables
}
